from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib import colors
import io
from .models import Transaction

def generate_pdf_confirmation(transaction: Transaction) -> bytes:
    """
    Generuje plik PDF z potwierdzeniem przelewu w pamięci (buffer).
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # --- Header ---
    c.setFillColor(colors.darkblue)
    c.rect(0, height - 3*cm, width, 3*cm, fill=1, stroke=0)
    
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(2*cm, height - 2*cm, "FINTECH CORE SYSTEM")
    c.setFont("Helvetica", 12)
    c.drawString(2*cm, height - 2.8*cm, "Electronic Transfer Confirmation")

    # --- Content ---
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, height - 5*cm, "Transaction Details")
    
    # Draw line
    c.setStrokeColor(colors.lightgrey)
    c.line(2*cm, height - 5.2*cm, width - 2*cm, height - 5.2*cm)

    # Data
    y = height - 7*cm
    line_height = 1.2*cm

    def draw_row(label, value):
        nonlocal y
        c.setFont("Helvetica", 12)
        c.setFillColor(colors.grey)
        c.drawString(2*cm, y, label)
        c.setFont("Helvetica-Bold", 12)
        c.setFillColor(colors.black)
        c.drawString(7*cm, y, str(value))
        y -= line_height

    draw_row("Date:", transaction.created_at.strftime("%Y-%m-%d %H:%M:%S"))
    draw_row("Amount:", f"{transaction.amount} {transaction.account.currency}")
    draw_row("Type:", transaction.transaction_type)
    draw_row("Title:", transaction.description)
    draw_row("Account:", transaction.account.account_number)
    draw_row("ID:", str(transaction.id))

    # --- Footer ---
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.grey)
    c.drawString(2*cm, 2*cm, "This document is generated electronically and does not require a signature.")
    c.drawString(2*cm, 1.5*cm, f"Generated by Fintech Core Microservice | {transaction.id}")

    c.showPage()
    c.save()
    
    buffer.seek(0)
    return buffer.getvalue()
