# Generated by Django 5.2.9 on 2025-12-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Wpłata'), ('WITHDRAWAL', 'Wypłata'), ('TRANSFER_IN', 'Przelew Przychodzący'), ('TRANSFER_OUT', 'Przelew Wychodzący')], max_length=20),
        ),
    ]
